buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
    }
    dependencies { classpath 'com.android.tools.build:gradle:8.9.2' }
}
allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
    }
}
tasks.register('clean', Delete) { delete rootProject.layout.buildDirectory }
